version: '3.7'
services:
  mongodb_container:
    container_name: mongo
    image: mongo:5.0
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - ~/mongodb-data/monogodb-docker-data:/data/db
