version: '3.7'
services:
  mongodb_container:
    container_name: my-mongo-1
    image: mongo:4.2
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - /Users/adampridmore/work/mongodb-data:/data/db
